### PR TITLE
First pass at building with Meson

### PR DESCRIPTION
**Pull request by llasram**
Same caveats per jdykstra/ucsd-psystem-vm#9.

### CODE REVIEW

**Comment by llasram** [comment]
@jdykstra Yes, I believe this is ready for review and merging.  The force-pushes were because I realized a few things while doing `xc` that should be slightly different -- in retrospect I should have written the Meson builds for all of the projects first, then opened the PRs.

(I do still need to do `os`, but I don't anticipate it influencing the others in the same way.)

**Comment by jdykstra** [comment]
The meson commit that was merged into jdykstra/ucsd-psystem-vm was the first one I received, not the last.  Please do a diff between that repo and yours and create a commit for whatever needs to be updated.  Thanks!

**Comment by llasram** [comment]
According to `git cherry` the commit merged for jdykstra/ucsd-psystem-vm#9 is the same as the HEAD of my `meson` branch.  I apologize for the confusion, and will avoid force-pushing open PR branches in the future!

**Comment by jdykstra** [comment]
Cool.  I just wanted to make sure things didn't get dropped.

**Pull request merged**
